<?php

declare(strict_types=1);

namespace app\Modules\Sync\Domain\DTO\Imuis;

use App\Shared\Infrastructure\DTO\BaseDTO;

final readonly class DebDTO extends BaseDTO
{
    public ?string $hash;

    public function __construct(
        public int $connect_id = 0,
        ?string $hash = null,
        public ?string $aanhef = null,
        public ?bool $aanm = null,
        public ?string $aanmafdruk = null,
        public ?string $aanmvast = null,
        public ?string $adres = null,
        public ?string $adressering = null,
        public ?int $betaler = null,
        public ?int $betcond = null,
        public ?bool $blok = null,
        public ?string $blokdeclva = null,
        public ?string $blokvrkva = null,
        public ?string $bnkbnkrek = null,
        public ?string $bnkbnkrek2 = null,
        public ?string $bnkgiro = null,
        public ?string $bnkgrek = null,
        public ?string $bnkiban = null,
        public ?string $bnkiban2 = null,
        public ?string $bnkrek = null,
        public ?string $bnkrek2 = null,
        public ?int $bnkreknum = null,
        public ?int $bnkreknum2 = null,
        public ?string $bnksrtinc = null,
        public ?string $btwnr = null,
        public ?string $btwpl = null,
        public ?string $datbtwnr = null,
        public ?string $datklantaf = null,
        public ?string $datklantsinds = null,
        public ?string $datkrlimtm = null,
        public ?string $datkrlimvan = null,
        public ?string $datkvkuittr = null,
        public ?string $datlstaanm = null,
        public ?string $datlstbet = null,
        public ?string $datlstfact = null,
        public ?string $datoprichting = null,
        public ?string $decbudverpl = null,
        public ?string $decltoel = null,
        public ?int $eannr = null,
        public ?string $email = null,
        public ?string $emailmailingjn = null,
        public ?int $extaanbrengrel = null,
        public ?string $extaanbrengzksl = null,
        public ?string $factafdruk = null,
        public ?bool $factoring = null,
        public ?string $facvrknaardeb = null,
        public ?string $fax = null,
        public ?string $gebrstaffel = null,
        public ?string $gebrverkkostpr = null,
        public ?string $giro = null,
        public ?string $giroiban = null,
        public ?string $gironaam = null,
        public ?int $gironum = null,
        public ?string $grek = null,
        public ?string $grekiban = null,
        public ?int $greknum = null,
        public ?int $grpdeb = null,
        public ?bool $heeftsaldo = null,
        public ?int $hnr = null,
        public ?string $hnrtv = null,
        public ?string $homepage = null,
        public ?string $incselafdruk = null,
        public ?int $inkcomb = null,
        public ?int $jrdecltm = null,
        public ?int $jrdeclvan = null,
        public ?int $kdr = null,
        public ?string $kenmopp = null,
        public ?string $kixcd = null,
        public ?string $klantaftekst = null,
        public ?string $klantsindstekst = null,
        public ?int $kpl = null,
        public ?float $krlim = null,
        public ?string $kvknr = null,
        public ?string $kvkplaats = null,
        public ?bool $laagstebedr = null,
        public ?string $land = null,
        public ?string $levcond = null,
        public ?string $medew = null,
        public ?string $medewaanbreng = null,
        public ?string $medewdec = null,
        public ?string $medewfiscaal = null,
        public ?string $medewloon = null,
        public ?string $medewvennoot = null,
        public ?string $mobiel = null,
        public ?string $naam = null,
        public ?string $naam2 = null,
        public ?int $nr = null,
        public ?string $nrbijdeb = null,
        public ?int $nrrit = null,
        public ?string $offafdruk = null,
        public ?string $opdrwz = null,
        public ?string $opm = null,
        public ?string $ordbevafdruk = null,
        public ?string $ordercompleet = null,
        public ?string $ordsrt = null,
        public ?string $pakbemail = null,
        public ?float $percgrek = null,
        public ?string $plaats = null,
        public ?float $plm = null,
        public ?int $pndecltm = null,
        public ?int $pndeclvan = null,
        public ?string $postcd = null,
        public ?string $prg = null,
        public ?int $prosp = null,
        public ?string $prslst = null,
        public ?int $rayon = null,
        public ?int $rit = null,
        public ?string $rvorm = null,
        public ?float $saldo = null,
        public ?int $sluitrek = null,
        public ?string $statnaam = null,
        public ?string $statplaats = null,
        public ?string $straat = null,
        public ?string $taal = null,
        public ?int $tegrek = null,
        public ?string $tel = null,
        public ?string $telprive = null,
        public ?float $teontvinc = null,
        public ?string $term = null,
        public ?string $termijnfact = null,
        public ?string $val = null,
        public ?string $vastectrdatum = null,
        public ?string $verkoper = null,
        public ?bool $verr = null,
        public ?string $verzfact = null,
        public ?string $verzwz = null,
        public ?string $voors = null,
        public ?string $vrijveld1 = null,
        public ?string $vrijveld2 = null,
        public ?string $vrijveld3 = null,
        public ?string $vrijveld4 = null,
        public ?string $vrijveld5 = null,
        public ?string $zksl = null,
    ) {
        if ($hash === null) {
            $data = $this->toArray();
            unset($data['zksl']);
            ksort($data);
            $this->hash = md5(json_encode($data));
        } else {
            $this->hash = $hash;
        }
    }
}
